### ISSUE TITLE
Throw exception on nonexistent filter

### ISSUE THREAD

**Issue by raphaeldealmeida** [rodrigojavornik/PHPCleanup#2]
https://github.com/rodrigojavornik/PHPCleanup/blob/bd26c2d6f31257f82014b23fe366707f4bd30e0e/library/Factory.php#L23

I couldn't get your idea for throw exception here.
The ReflectionClass already throws its own exception.

**Comment by rodrigojavornik** [comment]
thank you for your attention

In fact, it is not necessary to create another exception here.
